prefeiturasp/SME-CDEP

SME.CDEP.Dominio/Dominios/Usuario.cs, SME.CDEP.Infra.Dados/Mapeamentos/UsuarioMap.cs, scripts/V1__USUARIO_CREATE.sql
[AB#95126](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/95126)
=> Criação do script de criação da tabela

SME.CDEP.Aplicacao/Servicos/Interface/IServicoAplicacao.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoPerfilUsuario.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoUsuario.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_fazer_manutencao_usuario.cs
com tratamento de exceção no caso de serviço não registrado
=> Criado ObterServicoAplicacao para os testes na classe TesteBase

SME.CDEP.Aplicacao/Dtos/DadosUsuarioDTO.cs, SME.CDEP.Aplicacao/Integracoes/Interfaces/IServicoAcessos.cs, SME.CDEP.Aplicacao/Integracoes/ServicoAcessos.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoUsuario.cs, SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Entidades/Usuario.cs, SME.CDEP.TesteIntegracao/ConstantesTestes.cs, SME.CDEP.TesteIntegracao/ServicosFakes/ServicoAcessosFake.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_cadastrar_usuario_externo.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_fazer_autenticacao.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_fazer_manutencao_usuario.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_obter_meus_dados.cs, SME.CDEP.Webapi/Controllers/UsuarioController.cs
[AB#95385](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/95385)
=> Criação do endpoint de meus dados

SME.CDEP.Aplicacao/Dtos/DadosUsuarioDTO.cs, SME.CDEP.Aplicacao/Dtos/EnderecoTelefoneUsuarioExternoDTO.cs, SME.CDEP.Aplicacao/Dtos/RetornoBaseDTO.cs, SME.CDEP.Aplicacao/Integracoes/Interfaces/IServicoAcessos.cs, SME.CDEP.Aplicacao/Integracoes/ServicoAcessos.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoUsuario.cs, SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Dominio/Enumerados/TipoUsuario.cs, SME.CDEP.Dominio/Excecoes/NegocioException.cs, SME.CDEP.TesteIntegracao/ServicosFakes/ServicoAcessosFake.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_cadastrar_usuario_externo.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_fazer_autenticacao.cs, SME.CDEP.Webapi/Controllers/UsuarioController.cs, SME.CDEP.Webapi/Middlewares/TratamentoExcecaoGlobalMiddleware.cs
[AB#95386](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/95386)
[AB#95387](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/95387)
[AB#95392](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/95392)
=> feature/95386 - feature/95387

SME.CDEP.Aplicacao/Dtos/AlterarSenhaUsuarioDTO.cs, SME.CDEP.Aplicacao/Dtos/DadosUsuarioDTO.cs, SME.CDEP.Aplicacao/Dtos/EmailUsuarioDTO.cs, SME.CDEP.Aplicacao/Dtos/EnderecoTelefoneUsuarioExternoDTO.cs, SME.CDEP.Aplicacao/Dtos/EnderecoUsuarioExternoDTO.cs, SME.CDEP.Aplicacao/Dtos/RetornoBaseDTO.cs, SME.CDEP.Aplicacao/Dtos/TelefoneUsuarioExternoDTO.cs, SME.CDEP.Aplicacao/Integracoes/Interfaces/IServicoAcessos.cs, SME.CDEP.Aplicacao/Integracoes/ServicoAcessos.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoUsuario.cs, SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Dominio/Entidades/Usuario.cs, SME.CDEP.Dominio/Enumerados/TipoUsuario.cs, SME.CDEP.Dominio/Excecoes/NegocioException.cs, SME.CDEP.TesteIntegracao/ConstantesTestes.cs, SME.CDEP.TesteIntegracao/ServicosFakes/ServicoAcessosFake.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_cadastrar_usuario_externo.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_fazer_autenticacao.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_fazer_manutencao_usuario.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_obter_meus_dados.cs, SME.CDEP.Webapi/Controllers/UsuarioController.cs, SME.CDEP.Webapi/Middlewares/TratamentoExcecaoGlobalMiddleware.cs
[AB#93741](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/93741)
[AB#97307](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/97307)
=> CDEP - story/93741 --> RELEASE

SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoFormato.cs, SME.CDEP.Aplicacao/Servicos/ServicoFormato.cs, SME.CDEP.Dominio/Entidades/Formato.cs, SME.CDEP.Dominio/Entidades/Material.cs, SME.CDEP.Dominio/Entidades/Suporte.cs, SME.CDEP.Dominio/Enumerados/TipoFormato.cs, SME.CDEP.Infra.Dados/Mapeamentos/FormatoMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/MaterialMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/SuporteMap.cs, SME.CDEP.TesteIntegracao/ConstantesTestes.cs, SME.CDEP.TesteIntegracao/Formato/Ao_fazer_manutencao_formato.cs, SME.CDEP.TesteIntegracao/Material/Ao_fazer_manutencao_acesso_documento.cs, SME.CDEP.TesteIntegracao/Suporte/Ao_fazer_manutencao_acesso_documento.cs, SME.CDEP.Webapi/Controllers/AcessoDocumentoController.cs, SME.CDEP.Webapi/Controllers/ConservacaoController.cs, SME.CDEP.Webapi/Controllers/CromiaController.cs, SME.CDEP.Webapi/Controllers/FormatoController.cs, SME.CDEP.Webapi/Controllers/IdiomaController.cs, SME.CDEP.Webapi/Controllers/MaterialController.cs, SME.CDEP.Webapi/Controllers/SuporteController.cs, SME.CDEP.Webapi/Controllers/TipoAnexoController.cs, scripts/V5__CADASTROS_AUXILIARES_TABELAS.sql
[AB#99646](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/99646)
=> Alterações pós review

SME.CDEP.Aplicacao/Servicos/Interface/IServicoUsuario.cs, SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Webapi/Controllers/UsuarioController.cs
[AB#100736](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/100736)
=> Validar CPF existente

SME.CDEP.Aplicacao/Dtos/IdNomeExcluidoAuditavelDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Dominio/Constantes/Constantes.cs, SME.CDEP.Infra.Dados/Mapeamentos/AssuntoMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/AutorMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/CreditoMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/EditoraMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/SerieColecaoMap.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioBase.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/AcessoDocumento/Ao_fazer_manutencao_acesso_documento.cs, SME.CDEP.TesteIntegracao/Assunto/Ao_fazer_manutencao_assunto.cs, SME.CDEP.TesteIntegracao/Autor/Ao_fazer_manutencao_autor.cs, SME.CDEP.TesteIntegracao/Conservacao/Ao_fazer_manutencao_conservacao.cs, SME.CDEP.TesteIntegracao/Credito/Ao_fazer_manutencao_credito.cs, SME.CDEP.TesteIntegracao/Cromia/Ao_fazer_manutencao_cromia.cs, SME.CDEP.TesteIntegracao/Editora/Ao_fazer_manutencao_editora.cs, SME.CDEP.TesteIntegracao/Formato/Ao_fazer_manutencao_formato.cs, SME.CDEP.TesteIntegracao/Idioma/Ao_fazer_manutencao_idioma.cs, SME.CDEP.TesteIntegracao/Material/Ao_fazer_manutencao_acesso_documento.cs, SME.CDEP.TesteIntegracao/SerieColecao/Ao_fazer_manutencao_serie_colecao.cs, SME.CDEP.TesteIntegracao/Setup/RegistradorDependencias.cs, SME.CDEP.TesteIntegracao/Suporte/Ao_fazer_manutencao_acesso_documento.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.Webapi/Controllers/AssuntoController.cs, SME.CDEP.Webapi/Controllers/AutorController.cs, SME.CDEP.Webapi/Controllers/CreditoController.cs, SME.CDEP.Webapi/Controllers/EditoraController.cs, SME.CDEP.Webapi/Controllers/SerieColecaoController.cs, scripts/V9__CRIAR_CONSTRAINT_EVITAR_DUPLICACOES.sql
[AB#97227](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/97227)
=> Criação dos serviços, testes e endpoints

SME.CDEP.Aplicacao/Servicos/ServicoAplicacaoAuditavel.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.TesteIntegracao/Assunto/Ao_fazer_manutencao_assunto.cs, SME.CDEP.TesteIntegracao/Autor/Ao_fazer_manutencao_autor.cs, SME.CDEP.TesteIntegracao/Credito/Ao_fazer_manutencao_credito.cs, SME.CDEP.TesteIntegracao/Editora/Ao_fazer_manutencao_editora.cs, SME.CDEP.TesteIntegracao/SerieColecao/Ao_fazer_manutencao_serie_colecao.cs
[AB#101785](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/101785)
=> Ajuste para evitar cadastros inválidos

SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervo.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoIdNome.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervo.cs, SME.CDEP.Dominio/Enumerados/TipoAcervo.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/Setup/RegistradorDependencias.cs, SME.CDEP.Webapi/Controllers/AcervoController.cs
[AB#97605](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/97605)
=> Criar endpoint Tipo de Acervos

SME.CDEP.Dominio/Entidades/AcervoFotografico.cs, SME.CDEP.Dominio/Entidades/AcervoFotograficoArquivo.cs, SME.CDEP.Dominio/Entidades/Arquivo.cs, SME.CDEP.Dominio/Enumerados/TipoArquivo.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoFotograficoArquivoMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoFotograficoMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/ArquivoMap.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs
[AB#97604](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/97604)
=> Criar mapeamentos e entidades

scripts/V13__TABELA_ACERVO_ARTES_GRAFICAS.sql
=> Criar script SQL com a estrutura das tabelas

SME.CDEP.Dominio/Entidades/AcervoArteGrafica.cs, SME.CDEP.Dominio/Entidades/AcervoArteGraficaArquivo.cs, SME.CDEP.Dominio/Entidades/AcervoArteGraficaCompleto.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoArteGraficaArquivoMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoArteGraficaMap.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoArteGrafica.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoArteGraficaArquivo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoArteGrafica.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoArteGraficaArquivo.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs
=> Repositórios, entidades e mapeamentos do acervo arte gráfica

SME.CDEP.Aplicacao/DTOS/AcervoArteGraficaAlteracaoDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoArteGraficaCadastroDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoArteGraficaDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoArteGrafica.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoArteGraficaDTO.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoArteGraficaManutencao.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoAuditavel.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoFotografico.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoFotograficoManutencao.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoManutencao.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoPesquisa.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoTipos.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoArteGrafica.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoFotografico.cs, SME.CDEP.Dominio/Constantes/Constantes.cs, SME.CDEP.Dominio/Enumerados/TipoArquivo.cs, SME.CDEP.Dominio/Extensions/StringExtension.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoArteGrafica.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/AcervoArteGrafica/Ao_fazer_manutencao_acervo_arte_grafica.cs, SME.CDEP.TesteIntegracao/ConstantesTestes.cs, SME.CDEP.TesteIntegracao/Setup/RegistradorDependencias.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.Webapi/Controllers/AcervoArteGraficaController.cs, scripts/V13__TABELA_ACERVO_ARTES_GRAFICAS.sql
=> Criar endpoint de cadastro de acervo

SME.CDEP.Dominio/Entidades/AcervoTridimensional.cs, SME.CDEP.Dominio/Entidades/AcervoTridimensionalArquivo.cs, SME.CDEP.Dominio/Entidades/AcervoTridimensionalCompleto.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoTridimensionalArquivoMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoTridimensionalMap.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoTridimensional.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoTridimensionalArquivo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoTridimensional.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoTridimensionalArquivo.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs
=> Criar mapeamentos e entidades - tridimensional

SME.CDEP.Aplicacao/DTOS/AcervoTridimensionalAlteracaoDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoTridimensionalCadastroDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoTridimensionalDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoTridimensional.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoTridimensionalManutencao.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoTridimensional.cs, SME.CDEP.Dominio/Constantes/Constantes.cs, SME.CDEP.Dominio/Enumerados/TipoArquivo.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/AcervoArteGrafica/Ao_fazer_manutencao_acervo_arte_grafica.cs, SME.CDEP.TesteIntegracao/AcervoTridimensional/Ao_fazer_manutencao_acervo_tridimensional.cs, SME.CDEP.TesteIntegracao/Setup/RegistradorDependencias.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.Webapi/Controllers/AcervoTridimensionalController.cs
=> Criar endpoint de cadastro de acervo - Tridimensional

scripts/V15__TABELA_ACERVO_AUDIO_VISUAL.sql
=> Adicionando a tabela de audiovisual

SME.CDEP.Aplicacao/DTOS/AcervoAudiovisualAlteracaoDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoAudiovisualCadastroDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoAudiovisualDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoAudiovisual.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoAudiovisualManutencao.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoAudiovisual.cs, SME.CDEP.Dominio/Constantes/Constantes.cs, SME.CDEP.Dominio/Entidades/AcervoAudiovisual.cs, SME.CDEP.Dominio/Entidades/AcervoAudiovisualCompleto.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoAudiovisualMap.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoAudiovisual.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoAudiovisual.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/AcervoAudiovisual/Ao_fazer_manutencao_acervo_audiovisual.cs, SME.CDEP.TesteIntegracao/ConstantesTestes.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.Webapi/Controllers/AcervoAudiovisualController.cs
=> Adicionando entidades, mapeamentos, repositórios

SME.CDEP.Dominio/Entidades/Acervo.cs, SME.CDEP.Dominio/Entidades/AcervoDocumental.cs, SME.CDEP.Dominio/Entidades/AcervoDocumentalAcessoDocumento.cs, SME.CDEP.Dominio/Entidades/AcervoDocumentalArquivo.cs, SME.CDEP.Dominio/Entidades/AcervoDocumentalCompleto.cs, SME.CDEP.Dominio/Entidades/AcessoDocumentoResumido.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoDocumentalAcessoDocumentoMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoDocumentalArquivoMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoDocumentalMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoMap.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoDocumental.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoDocumentalAcessoDocumento.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoDocumentalArquivo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoDocumental.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoDocumentalAcessoDocumento.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoDocumentalArquivo.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs
[AB#97652](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/97652)
=> Criação das entidades, mapeamentos e repositórios

SME.CDEP.Aplicacao/DTOS/AcervoAudiovisualAlteracaoDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoAudiovisualCadastroDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoAudiovisualDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoAudiovisual.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoAudiovisualManutencao.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoAudiovisual.cs, SME.CDEP.Dominio/Constantes/Constantes.cs, SME.CDEP.Dominio/Entidades/AcervoAudiovisual.cs, SME.CDEP.Dominio/Entidades/AcervoAudiovisualCompleto.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoAudiovisualMap.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoAudiovisual.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoAudiovisual.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/AcervoAudiovisual/Ao_fazer_manutencao_acervo_audiovisual.cs, SME.CDEP.TesteIntegracao/ConstantesTestes.cs, SME.CDEP.TesteIntegracao/Setup/RegistradorDependencias.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.Webapi/Controllers/AcervoAudiovisualController.cs, scripts/V15__TABELA_ACERVO_AUDIO_VISUAL.sql
[AB#93736](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/93736)
[AB#105316](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/105316)
=> BACK - Story/93736 --> RELEASE

SME.CDEP.Dominio/Entidades/AcervoAudiovisual.cs, SME.CDEP.Dominio/Entidades/AcervoAudiovisualCompleto.cs
[AB#105990](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/105990)
=> Ajustando retorno de campos não obrigatórios

SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs, SME.CDEP.Dominio/Extensions/LongExtension.cs
[AB#106795](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/106795)
=> Ajustar a mensagem de crítica do campo antigo

SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervo.cs, SME.CDEP.TesteIntegracao/Acervo/Ao_fazer_manutencao_acervo.cs
[AB#106798](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/106798)
=> Campo Título pode ser duplicado desde que código ou tombo sejam diferentes

SME.CDEP.Webapi/Controllers/AssuntoController.cs, SME.CDEP.Webapi/Controllers/EditoraController.cs, SME.CDEP.Webapi/Controllers/SerieColecaoController.cs
[AB#97683](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/97683)
[AB#97684](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/97684)
[AB#97685](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/97685)
=> Criação do endpoint assunto, série coleção e editora

SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs, SME.CDEP.Dominio/Extensions/LongExtension.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervo.cs, SME.CDEP.TesteIntegracao/Acervo/Ao_fazer_manutencao_acervo.cs
[AB#107607](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/107607)
=> Ajuste de validações de título e código

SME.CDEP.Webapi/Modelos/planilha_acervo_arte_grafica.csv, SME.CDEP.Webapi/Modelos/planilha_acervo_audiovisual.csv, SME.CDEP.Webapi/Modelos/planilha_acervo_bibliografico.csv, SME.CDEP.Webapi/Modelos/planilha_acervo_documental.csv, SME.CDEP.Webapi/Modelos/planilha_acervo_fotografico.csv, SME.CDEP.Webapi/Modelos/planilha_acervo_tridimensional.csv
[AB#105229](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/105229)
=> Elaborar as planilhas modelo

SME.CDEP.Aplicacao/DTOS/AcervoBibliograficoLinhaDTO.cs, SME.CDEP.Aplicacao/DTOS/ImportacaoArquivoDTO.cs, SME.CDEP.Aplicacao/DTOS/LinhaConteudoAjustarDTO.cs, SME.CDEP.Aplicacao/DTOS/LinhaDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivo.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoManutencao.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivo.cs, SME.CDEP.Dominio/Entidades/ImportacaoArquivo.cs, SME.CDEP.Dominio/Entidades/ImportacaoArquivoCompleto.cs, SME.CDEP.Dominio/Enumerados/ImportacaoStatus.cs, SME.CDEP.Dominio/Extensions/ImportacaoStatusExtension.cs, SME.CDEP.Dominio/Extensions/TipoAcervoExtension.cs, SME.CDEP.Dominio/SME.CDEP.Dominio.csproj, SME.CDEP.Infra.Dados/Mapeamentos/ImportacaoArquivoMap.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioImportacaoArquivo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioImportacaoArquivo.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/AcervoBibliografico/Ao_fazer_manutencao_acervo_bibliografico.cs, SME.CDEP.TesteIntegracao/BaseMock.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo.cs, SME.CDEP.TesteIntegracao/Setup/RegistradorDependencias.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, scripts/V21__TABELA_IMPORTACAO_ARQUIVO.sql
[AB#105228](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/105228)
=> Criar Script SQL, Domínio, Mapeamentos e Repositórios

SME.CDEP.Aplicacao/DTOS/AcervoTridimensionalLinhaDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoTridimensionalLinhaRetornoDTO.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoTridimensional.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoTridimensional.cs, SME.CDEP.Dominio/Constantes/Constantes.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/BaseMock.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_tridimensional.cs, SME.CDEP.TesteIntegracao/Setup/RegistradorDependencias.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.Webapi/Controllers/ImportacaoArquivoAcervoTridimensionalController.cs
[AB#108113](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/108113)
=> Importação de acervo tridimensional

SME.CDEP.Webapi/Controllers/ArmazenamentoController.cs
This reverts commit a13995cad7e6d8803abb798057d88de2b54eac9c.
=> Revert "Ajuste de content disposition"

SME.CDEP.Webapi/Controllers/ImportacaoArquivoAcervoArteGraficaController.cs
This reverts commit 11a6cc264eeeac3f720fa90f749db6a78f659ad2.
=> Revert "Ajustando a rota para ficar mais legível"

SME.CDEP.Infra.Dados/Repositorios/RepositorioImportacaoArquivo.cs
[AB#109300](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/109300)
=> Tratamento para quando não encontrar importações

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoBase.cs
[AB#109320](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/109320)
=> Corrreção na avaliação de assuntos e créditos/autoresids

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoArteGrafica.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoAudiovisual.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoFotografico.cs
[AB#109560](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/109560)
=> Ajuste de crédito conforme o tipo de autoria

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoArteGrafica.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoAudiovisual.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoBibliografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoDocumental.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoFotografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoTridimensional.cs, SME.CDEP.Dominio/Constantes/Constantes.cs
[AB#109635](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/109635)
=> Somente permitir cadastro dos domínios que estão validados

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoArteGrafica.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoAudiovisual.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoBibliografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoDocumental.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoFotografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoTridimensional.cs
[AB#109635](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/109635)
=> Aplicar validação no campo e não na linha

SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoArteGrafica.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoAudiovisual.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoBibliografico.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoDocumental.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoFotografico.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoTridimensional.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoArteGrafica.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoAudiovisual.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoBibliografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoDocumental.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoFotografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoTridimensional.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoBase.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioImportacaoArquivo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioImportacaoArquivo.cs, SME.CDEP.Webapi/Controllers/ImportacaoArquivoAcervoArteGraficaController.cs, SME.CDEP.Webapi/Controllers/ImportacaoArquivoAcervoAudiovisualController.cs, SME.CDEP.Webapi/Controllers/ImportacaoArquivoAcervoBibliograficoController.cs, SME.CDEP.Webapi/Controllers/ImportacaoArquivoAcervoDocumentalController.cs, SME.CDEP.Webapi/Controllers/ImportacaoArquivoAcervoFotograficoController.cs, SME.CDEP.Webapi/Controllers/ImportacaoArquivoAcervoTridimensionalController.cs
[AB#109703](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/109703)
=> Tratamento de acesso documento e exposição de um método para consulta de importações

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoBase.cs
[AB#109744](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/109744)
=> Não estava comparando corretamente - sem lower

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoArteGrafica.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoAudiovisual.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoBibliografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoFotografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoBase.cs
[AB#109740](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/109740)
=> Tratamento de assuntos e créditos/autores

SME.CDEP.Aplicacao/DTOS/AcervoArteGraficaDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoFotograficoDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoTridimensionalDTO.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoBase.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_arte_grafica.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_audiovisual.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_bibliografico.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_documental.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_fotografico.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_tridimensional.cs
[AB#109740](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/109740)
[AB#109703](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/109703)
=> Correções diversas no retorno dos itens pendentes

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoTridimensional.cs
[AB#109928](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/109928)
=> Campo profundidade é double e não string

SME.CDEP.Aplicacao/DTOS/AcervoDocumentalCadastroDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoFotograficoCadastroDTO.cs, SME.CDEP.Dominio/Entidades/AcervoDocumental.cs, SME.CDEP.Dominio/Entidades/AcervoDocumentalCompleto.cs, SME.CDEP.Dominio/Entidades/AcervoFotografico.cs, SME.CDEP.Dominio/Entidades/AcervoFotograficoCompleto.cs, SME.CDEP.TesteIntegracao/AcervoDocumental/Ao_fazer_manutencao_acervo_documental.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_documental.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_fotografico.cs, scripts/V23__ALTERAR_TABELA_CAMPO_COPIA_DIGITAL_OPCIONAL.sql
[AB#110038](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/110038)
=> Ajustando o campo cópia digital e permite uso de imagem como nulo

SME.CDEP.Aplicacao/DTOS/PesquisaAcervoDTO.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs, SME.CDEP.Dominio/Entidades/PesquisaAcervo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervo.cs
[AB#110988](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/110988)
=> Adicionando campo Ano

SME.CDEP.Aplicacao/DTOS/AcervoCadastroDTO.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoArteGrafica.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoAudiovisual.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoBibliografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoFotografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoTridimensional.cs
[AB#110256](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/110256)
=> Ajuste de sufixo de código/tombo, ajuste código/tombo duplicado, problemas de CoAutor

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoArteGrafica.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoAudiovisual.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoFotografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoTridimensional.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoBase.cs
[AB#110256](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/110256)
=> Ajuste de sufixo no campo de tombo

SME.CDEP.Aplicacao/Servicos/Interface/IServicoDownloadArquivo.cs, SME.CDEP.Aplicacao/Servicos/ServicoDownloadArquivo.cs, SME.CDEP.Infra.Servicos/ServicoArmazenamento/ServicoArmazenamento.cs, SME.CDEP.Webapi/Controllers/ArmazenamentoController.cs
[AB#107847](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/107847)
=> Converter para JPEG imagens do tipo TIFF e TIF

SME.CDEP.Aplicacao/DTOS/ArquivoArmazenadoDTO.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoArmazenamentoArquivoFisico.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoDownloadArquivo.cs, SME.CDEP.Aplicacao/Servicos/ServicoArmazenamentoArquivoFisico.cs, SME.CDEP.Aplicacao/Servicos/ServicoDownloadArquivo.cs, SME.CDEP.Aplicacao/Servicos/ServicoUploadArquivo.cs, SME.CDEP.Dominio/Constantes/Constantes.cs, SME.CDEP.Dominio/Entidades/Arquivo.cs, SME.CDEP.Dominio/Extensions/StringExtension.cs, SME.CDEP.Infra.Dados/Mapeamentos/ArquivoMap.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioArquivo.cs
[AB#107847](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/107847)
=> Convertendo imagens para jpeg quando for tipo tif

SME.CDEP.Dominio/Enumerados/Permissao.cs, SME.CDEP.Webapi/Controllers/Filtros/PermissaoAttribute.cs
[AB#111651](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/111651)
=> B - Ajustar permissões e atributos

SME.CDEP.Aplicacao/DTOS/AutenticacaoRevalidarDTO.cs, SME.CDEP.Aplicacao/Integracoes/ConstantesServicoAcessos.cs, SME.CDEP.Aplicacao/Integracoes/Interfaces/IServicoAcessos.cs, SME.CDEP.Aplicacao/Integracoes/ServicoAcessos.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoUsuario.cs, SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Dominio/Entidades/Usuario.cs, SME.CDEP.Dominio/Extensions/JsonExtensao.cs, SME.CDEP.TesteIntegracao/ServicosFakes/ServicoAcessosFake.cs, SME.CDEP.Webapi/Controllers/AutenticacaoController.cs
[AB#111652](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/111652)
=> B - Criar dois endpoints em AutenticacaoController

SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoArteGrafica.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoFotografico.cs
[AB#112032](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/112032)
=> Correção da exibição de imagens respeitando 'permite uso de imagem' do acervo

SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervo.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioParametroSistema.cs, SME.CDEP.Webapi/Controllers/AcervoController.cs
[AB#108913](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/108913)
=> BACK - Criar endpoint - Termo de compromisso

SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Enumerados/SituacaoSolicitacaoItem.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_fazer_manutencao_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.Webapi/Controllers/AcervoSolicitacaoController.cs
[AB#108358](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/108358)
=> Paginando resultados

SME.CDEP.Aplicacao/DTOS/ResponsavelDTO.cs, SME.CDEP.Aplicacao/Integracoes/ConstantesServicoAcessos.cs, SME.CDEP.Aplicacao/Integracoes/Interfaces/IServicoAcessos.cs, SME.CDEP.Aplicacao/Integracoes/ServicoAcessos.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoUsuario.cs, SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.TesteIntegracao/ServicosFakes/ServicoAcessosFake.cs, SME.CDEP.Webapi/Controllers/UsuarioController.cs
[AB#108372](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/108372)
=> BACK - Criar endpoint - Listagem de responsáveis

SME.CDEP.Aplicacao/DTOS/FiltroSolicitacaoDTO.cs, SME.CDEP.Aplicacao/DTOS/MinhaSolicitacaoDTO.cs, SME.CDEP.Aplicacao/DTOS/SituacaoItemDTO.cs, SME.CDEP.Aplicacao/DTOS/SolicitacaoDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoUsuario.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Constantes/Constantes.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItemDetalhe.cs, SME.CDEP.Dominio/Enumerados/SituacaoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_fazer_manutencao_acervo_solicitacao.cs, SME.CDEP.Webapi/Controllers/AcervoSolicitacaoController.cs, SME.CDEP.Webapi/Controllers/UsuarioController.cs
[AB#108364](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/108364)
=> BACK - Criar endpoint - Tela de listagem de atendimentos

SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs
[AB#113462](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/113462)
=> Ajuste no retorno da descrição do enun

SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs
[AB#113500](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/113500)
=> Ajustando o parâmetro de usuario

SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
[AB#113641](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/113641)
=> Ajustando o retorno do tipo de acervo

SME.CDEP.Aplicacao/DTOS/DadosUsuarioDTO.cs, SME.CDEP.Aplicacao/DTOS/UsuarioDTO.cs, SME.CDEP.Aplicacao/DTOS/UsuarioExternoDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Entidades/Usuario.cs, SME.CDEP.Infra.Dados/Mapeamentos/UsuarioMap.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioUsuario.cs, SME.CDEP.TesteIntegracao/Mocks/UsuarioDTOMock.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_cadastrar_usuario_externo.cs, scripts/V31__ALTER_TABLE_USUARIO_ADD_INSTITUICAO.sql
[AB#113512](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/113512)
=> 2) BACK - No cadastro de usuários deverá ser criado um campo para informação da Instituição/Empresa, de preenchimento obrigatório.

SME.CDEP.Aplicacao/DTOS/AcervoArteGraficaDetalheDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoBibliograficoDetalheDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoDocumentalDetalheDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoFotograficoDetalheDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoTridimensionalDetalheDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
[AB#113525](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/113525)
=> 9) BACK - Na visualização dos acervos deverá ser acrescentada a unidade de medida (cm)

SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs
[AB#114014](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/114014)
=> Erro de merge

SME.CDEP.Aplicacao/DTOS/AcervoDetalheDTO.cs
[AB#114372](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/114372)
=> Ajuste do tipo de dado do ANO

SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoDetalheDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoItemDetalheResumidoDTO.cs, SME.CDEP.Aplicacao/DTOS/DadosSolicitanteDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoUsuario.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacao.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoDetalhe.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItemDetalheResumido.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoSolicitacaoMap.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacao.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_fazer_manutencao_acervo_solicitacao.cs, SME.CDEP.Webapi/Controllers/AcervoSolicitacaoController.cs, scripts/V33__ALTER_TABLE_ACERVO_SOLICITACAO_DATA_VISITA_RESPONSAVEL.sql, scripts/V33__ALTER_TABLE_ACERVO_SOLICITACAO_RESPONSAVEL.sql
Retornar as informações da solicitação, do itens dos acervos e do usuário solicitante
[AB#108368](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/108368)
=> feature: BACK - Criar endpoint - Tela detalhes da solicitação

SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoConfirmarDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoItemConfirmarDTO.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacao.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItem.cs, SME.CDEP.Dominio/Enumerados/SituacaoSolicitacao.cs, SME.CDEP.Dominio/Enumerados/SituacaoSolicitacaoItem.cs, SME.CDEP.Dominio/Enumerados/TipoAtendimento.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoSolicitacaoItemMap.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_confirmar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_fazer_manutencao_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_obter_detalhes_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_pesquisar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.Webapi/Controllers/AcervoSolicitacaoController.cs, scripts/V33__ALTER_TABLE_ACERVO_SOLICITACAO_RESPONSAVEL.sql
[AB#108375](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/108375)
=> Feature: BACK - Criar endpoint - Confirmar atendimento

SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Dominio/Enumerados/SituacaoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_finalizar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.Webapi/Controllers/AcervoSolicitacaoController.cs
[AB#108376](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/108376)
=> Feature: BACK - Criar endpoint - Finalizar atendimento

SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Dominio/Enumerados/SituacaoSolicitacao.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_cancelar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_cancelar_acervo_solicitacao_item.cs, SME.CDEP.Webapi/Controllers/AcervoSolicitacaoController.cs
[AB#108377](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/108377)
=> Feature: BACK - Criar endpoint - Cancelar atendimento

SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoItemRetornoCadastroDTO.cs, SME.CDEP.Aplicacao/DTOS/AlterarDataVisitaAcervoSolicitacaoItemDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItemCompleto.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_alterar_data_visita_acervo_solicitacao_item.cs, SME.CDEP.Webapi/Controllers/AcervoSolicitacaoController.cs
[AB#108920](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/108920)
=> Feature: BACK - Criar endpoint - Edição da solicitação

SME.CDEP.Aplicacao/Servicos/Interface/IServicoUsuario.cs, SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Webapi/Controllers/UsuarioController.cs
[AB#111674](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/111674)
=> Feature: B - Avaliar retorno das informações do usuário

SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Enumerados/SituacaoAtendimento.cs, SME.CDEP.Webapi/Controllers/AcervoSolicitacaoController.cs
[AB#111676](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/111676)
=> Feature: B - Endpoint situação do atendimento:

SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervo.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervo.cs, SME.CDEP.Webapi/Controllers/AcervoController.cs
[AB#108995](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/108995)
=> Feature: B - Pesquisar acervo por tombo/código

SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoItemManualCadastroDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoManualCadastroDTO.cs, SME.CDEP.Aplicacao/DTOS/IdNomeCodigoDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervo.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacao.cs, SME.CDEP.Dominio/Enumerados/Origem.cs, SME.CDEP.Dominio/Enumerados/SituacaoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoSolicitacaoMap.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervo.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_fazer_acervo_solicitacao_manual.cs, SME.CDEP.Webapi/Controllers/AcervoController.cs, SME.CDEP.Webapi/Controllers/AcervoSolicitacaoController.cs, scripts/V34__ALTER_TABLE_ACERVO_SOLICITACAO_ORIGEM.sql
[AB#111677](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/111677)
=> Feature: B - Endpoint de persistência de atendimento manual

scripts/V35__ALTER_TABLE_CREDITO_AUTOR_REMOVER_UNIQUE_CONSTRAINT.sql
[AB#114265](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/114265)
=> Removendo a constraint - validação por query

SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
[AB#114266](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/114266)
=> Removendo os espaços em branco dos domínios que são retornados do banco de dados para avaliação na planilha de importação

SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Dominio/Entidades/AcervoArteGraficaDetalhe.cs, SME.CDEP.Dominio/Entidades/AcervoBibliograficoDetalhe.cs, SME.CDEP.Dominio/Entidades/AcervoDocumentalDetalhe.cs, SME.CDEP.Dominio/Entidades/AcervoFotograficoDetalhe.cs, SME.CDEP.Dominio/Entidades/AcervoTridimensionalDetalhe.cs, SME.CDEP.TesteIntegracao/AcervoArteGrafica/Ao_fazer_manutencao_acervo_arte_grafica.cs, SME.CDEP.TesteIntegracao/AcervoBibliografico/Ao_fazer_manutencao_acervo_bibliografico.cs, SME.CDEP.TesteIntegracao/AcervoDocumental/Ao_fazer_manutencao_acervo_documental.cs, SME.CDEP.TesteIntegracao/AcervoFotografico/Ao_fazer_manutencao_acervo_fotografico.cs, SME.CDEP.TesteIntegracao/AcervoTridimensional/Ao_fazer_manutencao_acervo_tridimensional.cs
[AB#114347](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/114347)
=> Ajustando a exibição dos campos de dimensões conforme o preenchimento

SME.CDEP.Aplicacao/DTOS/AcervoBibliograficoTelaDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoDocumentalDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoDocumentalDetalheDTO.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoDocumental.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_documental.cs
[AB#114335](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/114335)
=> Ajustando o campo número de páginas para inteiro

SME.CDEP.Dominio/Enumerados/Permissao.cs
[AB#115512](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/115512)
=> Adicionando permissionamento de gestão de visita - calendário

SME.CDEP.Aplicacao/DTOS/EventoCadastroDTO.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoEvento.cs, SME.CDEP.Aplicacao/Servicos/ServicoEvento.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioEvento.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioEvento.cs, SME.CDEP.TesteIntegracao/Evento/Ao_fazer_manutencao_evento.cs, SME.CDEP.Webapi/Controllers/EventoController.cs
[AB#111323](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/111323)
=> B - Criar um endpoint de exclusão de evento

SME.CDEP.Aplicacao/DTOS/CalendarioEventoDTO.cs, SME.CDEP.Aplicacao/DTOS/DiaDTO.cs, SME.CDEP.Aplicacao/DTOS/SemanaDTO.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoEvento.cs, SME.CDEP.Aplicacao/Servicos/ServicoEvento.cs, SME.CDEP.Dominio/Enumerados/DateTimeExtension.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioEvento.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioEvento.cs, SME.CDEP.TesteIntegracao/Evento/Ao_fazer_manutencao_evento.cs, SME.CDEP.Webapi/Controllers/EventoController.cs
[AB#111317](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/111317)
=> B - Criar endpoint que retorna a grade de dias do mês selecionado

SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs
[AB#114425](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/114425)
=> Removendo tags HTML da descrição do acervo

SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_cancelar_acervo_solicitacao.cs
[AB#115675](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/115675)
=> Permite cancelamento de atendimento em todas as situações, exceto quando itens em finalizado automaticamente

SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs
[AB#115678](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/115678)
=> Correção do cadastro do usuário quando ocorre o login

SME.CDEP.Aplicacao/DTOS/FiltroCodigoTomboDTO.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervo.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs, SME.CDEP.Webapi/Controllers/AcervoController.cs
[AB#115672](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/115672)
=> Aplicando validação no campo de código/tombo

SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs
[AB#115673](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/115673)
=> Correção da situação que permite finalizar atendimento

SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioEvento.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioEvento.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_alterar_acervo_solicitacao_manual.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_confirmar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_fazer_manutencao_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_inserir_acervo_solicitacao_manual.cs
[AB#111326](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/111326)
=> B - Validar preenchimento da 'Data da visita' não permitir em feriado e suspensão

SME.CDEP.Aplicacao/DTOS/FiltroSolicitacaoDTO.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_pesquisar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/TesteBase.cs
[AB#115743](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/115743)
=> B - Criar filtro por Solicitante

SME.CDEP.Aplicacao/DTOS/DiaMesDTO.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoEvento.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoEvento.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioEvento.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioEvento.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_alterar_acervo_solicitacao_manual.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_cancelar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_cancelar_acervo_solicitacao_item.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_confirmar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_inserir_acervo_solicitacao_manual.cs, SME.CDEP.TesteIntegracao/Evento/Ao_fazer_manutencao_evento.cs
[AB#111322](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/111322)
=> Correção dos testes de integração - cancelar atendimento, item, confirmar, inserir e alterar manual

SME.CDEP.Aplicacao/DTOS/EventoCadastroDTO.cs, SME.CDEP.Aplicacao/DTOS/EventoDetalheDTO.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoEvento.cs, SME.CDEP.Aplicacao/Servicos/ServicoEvento.cs, SME.CDEP.Aplicacao/UseCase/ExecutarCriacaoDeEventosTipoFeriadoAnoAtualUseCase.cs, SME.CDEP.Dominio/Entidades/EventoDetalhe.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioEvento.cs, SME.CDEP.Infra.Servicos/Mensageria/Exchange/ExchangeRabbit.cs, SME.CDEP.Infra.Servicos/Worker/WorkerRabbitCDEP.cs, SME.CDEP.TesteIntegracao/Evento/Ao_gerar_evento_fixos_moveis.cs, SME.CDEP.Webapi/Controllers/AcervoSolicitacaoController.cs, scripts/V37__CREATE_TABLE_EVENTOS_FIXOS.sql
[AB#111321](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/111321)
=> Feature/111321 - Complementar

SME.CDEP.Dominio/Entidades/TipoParametroSistema.cs, scripts/V38__CREATE_PARAMETRO_ENDERECO_CONFIRMACAO_CLD_ACERVO_SOLICITACAO.sql
[AB#115736](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/115736)
=> B - Criar parâmetro endereço do contato do CDEP

SME.CDEP.Aplicacao/Servicos/Interface/IServicoNotificacaoEmail.cs, SME.CDEP.Aplicacao/Servicos/ServicoNotificacaoEmail.cs, SME.CDEP.Aplicacao/UseCase/NotificarViaEmailCancelamentoAtendimento.cs, SME.CDEP.Aplicacao/UseCase/NotificarViaEmailCancelamentoAtendimentoItem.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItemDetalhe.cs, SME.CDEP.Dominio/Entidades/TipoParametroSistema.cs, scripts/V38__CREATE_PARAMETRO_ENDERECO_CONFIRMACAO_CLD_ACERVO_SOLICITACAO.sql
[AB#116025](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/116025)
=> B - Enviar e-mail quando cancelar item

SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/UseCase/NotificarViaEmailCancelamentoAtendimento.cs, SME.CDEP.Aplicacao/UseCase/NotificarViaEmailCancelamentoAtendimentoItem.cs, SME.CDEP.Aplicacao/UseCase/NotificarViaEmailConfirmacaoAtendimentoPresencial.cs, SME.CDEP.Dominio/Entidades/TipoParametroSistema.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs, scripts/V38__CREATE_PARAMETRO_ENDERECO_CONFIRMACAO_CLD_ACERVO_SOLICITACAO.sql
[AB#115735](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/115735)
=> Confirmação o envio de e-mail quando confirma visita

SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Constantes/Constantes.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs
[AB#116362](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/116362)
=> Aplicação de regex quando cria usuários externos e atualiza e-mail

SME.CDEP.Aplicacao/UseCase/NotificarViaEmailConfirmacaoAtendimentoPresencial.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs
[AB#116487](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/116487)
=> Notificar os confirmados somente nas situações que estão aguardando visita

SME.CDEP.Aplicacao/DTOS/DadosSolicitanteDTO.cs, SME.CDEP.Aplicacao/DTOS/EnderecoUsuarioExternoDTO.cs, SME.CDEP.Aplicacao/DTOS/UsuarioDTO.cs, SME.CDEP.Aplicacao/DTOS/UsuarioExternoDTO.cs, SME.CDEP.Dominio/Entidades/Usuario.cs, SME.CDEP.TesteIntegracao/Mocks/UsuarioDTOMock.cs, SME.CDEP.TesteIntegracao/ServicosFakes/ServicoMensageriaCDEPFake.cs, SME.CDEP.TesteIntegracao/ServicosFakes/ServicoMensageriaLogsFake.cs, SME.CDEP.TesteIntegracao/ServicosFakes/ServicoMensageriaMetricasFake.cs, SME.CDEP.TesteIntegracao/Setup/RegistradorDependencias.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_cadastrar_usuario_externo.cs, SME.CDEP.TesteIntegracao/Usuarios/Ao_obter_meus_dados.cs, scripts/V39__ALTER_TABLE_USUARIO_NUMERO_EH_TEXTO.sql
[AB#116355](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/116355)
=> Campo numero

SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Dominio/Enumerados/SituacaoSolicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_cancelar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_finalizar_acervo_solicitacao.cs
[AB#116234](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/116234)
=> B - Ajustar CANCELAR ATENDIMENTO e FINALIZAR ATENDIMENTO

SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoConfirmarDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoDetalheDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoItemDetalheResumidoDTO.cs, SME.CDEP.Aplicacao/DTOS/ConfirmarAtendimentoDTO.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/UseCase/NotificarViaEmailCancelamentoAtendimento.cs, SME.CDEP.Aplicacao/UseCase/NotificarViaEmailCancelamentoAtendimentoItem.cs, SME.CDEP.Aplicacao/UseCase/NotificarViaEmailConfirmacaoAtendimentoPresencial.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacao.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoDetalhe.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItem.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItemDetalheResumido.cs, SME.CDEP.Dominio/Enumerados/SituacaoSolicitacao.cs, SME.CDEP.Dominio/Enumerados/SituacaoSolicitacaoItem.cs, SME.CDEP.Dominio/Extensions/EnumerableStringExtension.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoSolicitacaoItemMap.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoSolicitacaoMap.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacao.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_alterar_acervo_solicitacao_manual.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_cancelar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_confirmar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_fazer_manutencao_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_finalizar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_inserir_acervo_solicitacao_manual.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, scripts/V40__ALTER_TABLE_ACERVO_SOLICITACAO_E_ITEM_MOVER_RESPONSAVEL.sql
[AB#115820](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/115820)
[AB#116848](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/116848)
=> BACK - Story/115820 --> RELEASE

SME.CDEP.Dominio/Entidades/AcervoEmprestimo.cs, SME.CDEP.Dominio/Entidades/TipoParametroSistema.cs, SME.CDEP.Dominio/Enumerados/SituacaoEmprestimo.cs, SME.CDEP.Infra.Dados/Mapeamentos/AcervoEmprestimoMap.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoEmprestimo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoEmprestimo.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/Acervo/Ao_fazer_manutencao_acervo.cs, SME.CDEP.TesteIntegracao/AcervoBibliografico/Ao_fazer_manutencao_acervo_bibliografico.cs, SME.CDEP.TesteIntegracao/AcervoEmprestimo/Ao_fazer_manutencao_acervo_emprestimo.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoArteGraficaMock.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoBibliograficoMock.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoEmprestimoMock.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoMock.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoSolicitacaoItemMock.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoSolicitacaoMock.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, scripts/V41__CREATE_TABLE_ACERVO_EMPRESTIMO.sql
[AB#111272](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/111272)
=> B - Criar SQL - Entidades - Mapeamentos - Repositórios

SME.CDEP.Webapi/Middlewares/TratamentoExcecaoGlobalMiddleware.cs
[AB#117310](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/117310)
=> Passando statusCode nos erros do middleware

SME.CDEP.Aplicacao/DTOS/AcervoTipoTituloAcervoIdCreditosAutoresDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoEmprestimo.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoEmprestimo.cs, SME.CDEP.Aplicacao/Servicos/ServicoEvento.cs, SME.CDEP.Dominio/Entidades/AcervoArteGraficaDetalhe.cs, SME.CDEP.Dominio/Entidades/AcervoTipoTituloAcervoIdCreditosAutores.cs, SME.CDEP.Dominio/Enumerados/TipoArquivo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacao.cs, SME.CDEP.TesteIntegracao/Acervo/Ao_detalhar_acervo.cs, SME.CDEP.TesteIntegracao/Acervo/Ao_fazer_pesquisa_acervo.cs, SME.CDEP.TesteIntegracao/AcervoEmprestimo/Ao_fazer_manutencao_acervo_emprestimo.cs, SME.CDEP.TesteIntegracao/Evento/Ao_gerar_evento_fixos_moveis.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoEmprestimoMock.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.Webapi/Controllers/AcervoEmprestimoController.cs
[AB#111278](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/111278)
=> B - Alterar a Situação do empréstimo quando acervo for devolvido

SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.TesteIntegracao/AcervoEmprestimo/Ao_fazer_manutencao_acervo_emprestimo.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_alterar_acervo_solicitacao_manual.cs, SME.CDEP.TesteIntegracao/TesteBase.cs
[AB#117784](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/117784)
=> Adicionando regras de negócio quanto as datas

SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Extensions/StringExtension.cs
[AB#117988](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/117988)
=> Removendo a máscara da caixa de texto

SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItem.cs
[AB#118035](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/118035)
=> Permitir datas passadas

SME.CDEP.Aplicacao/DTOS/UsuarioExternoDTO.cs, SME.CDEP.Aplicacao/Extensions/GuidExtension.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervo.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoSolicitacaoTipo.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoTipo.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoTipos.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoTipoAcervoPermitido.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoUsuario.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Extensions/LongExtension.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervo.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_pesquisar_acervo_por_codigo_tombo.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_pesquisar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/ConstantesTestes.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoArteGraficaMock.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoAudiovisualMock.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoDocumentalMock.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoFotograficoMock.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoTridimensionalMock.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.Webapi/Controllers/AcervoController.cs
[AB#117948](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/117948)
=> B - Listar somente solicitações com base no perfil e remover obrigatoriedade do campo instituição

SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoDetalheDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoItemDetalheResumidoDTO.cs, SME.CDEP.Aplicacao/DTOS/MinhaSolicitacaoDTO.cs, SME.CDEP.Aplicacao/DTOS/SolicitacaoDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItemDetalheResumido.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervo.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_confirmar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_fazer_manutencao_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_inserir_acervo_solicitacao_manual.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_obter_detalhes_acervo_solicitacao.cs
[AB#117895](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/117895)
=> Ajustando o retorno das propriedades para retornar data e hora formatada

SME.CDEP.Aplicacao/DTOS/UsuarioExternoDTO.cs, SME.CDEP.Aplicacao/Extensions/GuidExtension.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervo.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoSolicitacaoTipo.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoTipo.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoTipoAcervoPermitido.cs, SME.CDEP.Aplicacao/Servicos/Interface/IServicoUsuario.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Extensions/LongExtension.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervo.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacao.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacao.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_pesquisar_acervo_por_codigo_tombo.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_pesquisar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/ConstantesTestes.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoArteGraficaMock.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoAudiovisualMock.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoDocumentalMock.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoFotograficoMock.cs, SME.CDEP.TesteIntegracao/Mocks/AcervoTridimensionalMock.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, SME.CDEP.Webapi/Controllers/AcervoController.cs
[AB#117835](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/117835)
[AB#117590](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/117590)
=> BACK - Story/117835 --> RELEASE

SME.CDEP.Aplicacao/DTOS/AcervoBibliograficoDetalheDTO.cs, SME.CDEP.Aplicacao/DTOS/AcervoTipoTituloAcervoIdCreditosAutoresDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoAuditavel.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Dominio/Entidades/AcervoBibliograficoDetalhe.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItemDetalheResumido.cs, SME.CDEP.Dominio/Entidades/AcervoTipoTituloAcervoIdCreditosAutores.cs, SME.CDEP.Dominio/Entidades/PesquisaAcervo.cs, SME.CDEP.Dominio/Enumerados/SituacaoEmprestimo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoBibliografico.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacao.cs, SME.CDEP.TesteIntegracao/Acervo/Ao_detalhar_acervo.cs, SME.CDEP.TesteIntegracao/Acervo/Ao_fazer_pesquisa_acervo.cs, SME.CDEP.TesteIntegracao/Acervo/Ao_obter_itens_por_acervo_ids.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_cancelar_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_cancelar_acervo_solicitacao_item.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_obter_detalhes_acervo_solicitacao.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_pesquisar_acervo_por_codigo_tombo.cs, SME.CDEP.TesteIntegracao/Mocks/ParametroSistemaMock.cs, SME.CDEP.TesteIntegracao/TesteBase.cs, scripts/V42__ALTER_TABLE_ACERVO_BILIOGRAFICO_INCLUIR_SALDO.sql
[AB#115725](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/115725)
=> Aplicando controle de saldo nas visões

SME.CDEP.Aplicacao/Servicos/ServicoEvento.cs
[AB#118415](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/118415)
=> Adicionar horário nos eventos tbém

SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoItemDetalheResumidoDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs
[AB#118529](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/118529)
=> Retornando controle do botão finalizar item

SME.CDEP.Aplicacao/DTOS/AcervoSolicitacaoItemRetornoCadastroDTO.cs, SME.CDEP.Aplicacao/Mapeamentos/DominioParaDTOProfile.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItemCompleto.cs, SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItemDetalheResumido.cs, SME.CDEP.Dominio/Enumerados/SituacaoSaldo.cs, SME.CDEP.Dominio/Enumerados/SituacaoSolicitacao.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoEmprestimo.cs
[AB#118735](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/118735)
=> Aplicando retorno de situações na tela de minhas solicitações e filtro da execução da rotina de itens atrasados

SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoEmprestimo.cs
[AB#119067](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119067)
=> Estava decretando como atraso de devolução os empréstimos do dia atual tbém

SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItemCompleto.cs
[AB#119082](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119082)
=> Correção do nome da propriedade que retorna o AcervoSolicitacaoId

SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoEmprestimo.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoEmprestimo.cs, SME.CDEP.Aplicacao/UseCase/Interface/INotificacaoBaseUseCase.cs, SME.CDEP.Aplicacao/UseCase/Interface/INotificacaoDevolucaoEmprestimoAtrasadoUseCase.cs, SME.CDEP.Aplicacao/UseCase/Interface/INotificacaoDevolucaoEmprestimoAtrasadoUsuarioUseCase.cs, SME.CDEP.Aplicacao/UseCase/NotificacaoDevolucaoEmprestimoAtrasadoUseCase.cs, SME.CDEP.Aplicacao/UseCase/NotificacaoDevolucaoEmprestimoAtrasadoUsuarioUseCase.cs, SME.CDEP.Aplicacao/UseCase/NotificacaoEmailBaseUseCase.cs, SME.CDEP.Dominio/Entidades/AcervoEmprestimoDevolucao.cs, SME.CDEP.Dominio/Entidades/TipoParametroSistema.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoEmprestimo.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoEmprestimo.cs, SME.CDEP.Infra.Servicos/Rabbit/RotasRabbit.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/AcervoEmprestimo/Ao_notificar_devolucao_emprestimo_atrasado.cs, SME.CDEP.TesteIntegracao/AcervoEmprestimo/Ao_notificar_vencimento_emprestimo.cs, SME.CDEP.TesteIntegracao/Setup/RegistradorDependencias.cs, SME.CDEP.Worker/WorkerRabbitMQ.cs, scripts/V44__ADD_PARAMETRO_QTDE_DIAS_ATRASO_DEVOLUCAO_EMPRESTIMO.sql
[AB#117965](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/117965)
=> B - Notificar usuários do atraso na devolução

SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Dominio/Enumerados/DateTimeExtension.cs
[AB#118286](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/118286)
=> Data de devolução deve ser maior que empréstimo

SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Webapi/Controllers/AcervoSolicitacaoController.cs
[AB#119108](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119108)
=> Adicionando um endpoint exclusivo para o GET do Minhas solicitações - sem restrição de tipos via perfil

SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacao.cs
[AB#119106](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119106)
=> Correção do retorno do acervo

SME.CDEP.Dominio/Entidades/AcervoSolicitacaoItemDetalheResumido.cs, SME.CDEP.Dominio/Enumerados/SituacaoSaldo.cs
[AB#119281](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119281)
=> Desabilitar edições quando tiver emprestado somente

SME.CDEP.Aplicacao/Servicos/ServicoAcervoBibliografico.cs
[AB#119284](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119284)
=> Atualização de saldo somente para bibliográfico

SME.CDEP.Aplicacao/SME.CDEP.Aplicacao.csproj, scripts/V45__ALTER_TABLE_REMOVER_UNIQUE_SERIE_COLECAO_EDITORA_ASSUNTO.sql
[AB#119606](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119606)
=> Removendo a constraint duplicada que já existe com nome e excluido

scripts/V45__ALTER_TABLE_REMOVER_UNIQUE_SERIE_COLECAO_EDITORA_ASSUNTO.sql
[AB#119606](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119606)
=> Removendo a constraint do banco - já existe no código

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoBibliografico.cs, SME.CDEP.Dominio/Constantes/Constantes.cs, scripts/V46__ALTER_TABLE_ACERVO_BIBLIOGRAFICO_PERMITIR_30_CARACTERES.sql
[AB#119639](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119639)
=> Campo Edição passou a permitir 30 caracteres

SME.CDEP.Infra.Servicos/ServicoArmazenamento/ConfiguracaoArmazenamentoOptions.cs, SME.CDEP.Infra.Servicos/ServicoArmazenamento/ServicoArmazenamento.cs
[AB#119641](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119641)
=> Removendo referência a tag de url front

SME.CDEP.Dominio/Constantes/MensagemNegocio.cs
[AB#119646](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119646)
=> Melhoria na mensagem de erro dos campos dimensões

SME.CDEP.Aplicacao/DTOS/EventoDetalheDTO.cs, SME.CDEP.Aplicacao/Servicos/ServicoEvento.cs, SME.CDEP.Dominio/Entidades/EventoDetalhe.cs, SME.CDEP.Dominio/Enumerados/EnumExtensao.cs
[AB#119675](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119675)
=> Correção do retorno do calendário

SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Constantes/Constantes.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs
[AB#119710](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119710)
=> Correção da mensagem do usuário e máscara dos campos de dimensões

SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Infra.Dados/Repositorios/Interfaces/IRepositorioAcervoSolicitacaoItem.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioAcervoSolicitacaoItem.cs
[AB#120030](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/120030)
=> Correção da regra de alteração de data de visita

SME.CDEP.Aplicacao/Servicos/Interface/IServicoAcervoSolicitacao.cs, SME.CDEP.Aplicacao/Servicos/ServicoAcervoSolicitacao.cs, SME.CDEP.Dominio/Enumerados/SituacaoSolicitacaoItem.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_finalizar.cs, SME.CDEP.TesteIntegracao/AcervoSolicitacao/Ao_obter_detalhes_acervo_solicitacao.cs
[AB#120050](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/120050)
=> Correção do botão finalizar

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoDocumental.cs
[AB#119708](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/119708)
=> Acerdo documental não obriga o preenchimento do campo de autor

SME.CDEP.Dominio/Entidades/AcervoAudiovisualDetalhe.cs, SME.CDEP.Dominio/Entidades/AcervoFotograficoDetalhe.cs, SME.CDEP.Dominio/Entidades/AcervoTridimensionalDetalhe.cs
[AB#120295](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/120295)
=> Mudança da estrutura de dados do campo ANO

SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Enumerados/EnumExtensao.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioUsuario.cs
[AB#120291](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/120291)
=> Correção do retorno do enum

SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs, SME.CDEP.Dominio/Constantes/Constantes.cs, SME.CDEP.Dominio/Enumerados/TipoUsuario.cs
[AB#120327](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/120327)
=> Tratamento de usuários que são cadastrados diretamente pelo login e existentes no CoreSSO

SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoBibliografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoAssunto.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoBibliografico.cs, SME.CDEP.Aplicacao/UseCase/ExecutarImportacaoArquivoAcervoBibliograficoUseCase.cs, SME.CDEP.Aplicacao/UseCase/Interface/IExecutarImportacaoArquivoAcervoBibliograficoUseCase.cs, SME.CDEP.Dominio/Constantes/Constantes.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Infra.Servicos/Rabbit/RotasRabbit.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_bibliografico.cs, SME.CDEP.Worker/WorkerRabbitMQ.cs
=> Importação de acervos bibliográficos em fila

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoBibliografico.cs, scripts/V48__ALTER_AUMENTAR_CAMPO_NOME_ASSUNTO_PARA_270.sql
=> Aumentando o campo tipo autoria para 30 caracteres

scripts/V48__ALTER_AUMENTAR_CAMPO_NOME_ASSUNTO_PARA_270.sql
=> Correção do script

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoArteGrafica.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoAudiovisual.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoDocumental.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoFotografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoTridimensional.cs, SME.CDEP.Aplicacao/UseCase/ExecutarImportacaoArquivoAcervoBibliograficoUseCase.cs, SME.CDEP.Dominio/Enumerados/ImportacaoStatus.cs, SME.CDEP.Infra.Dados/Repositorios/RepositorioImportacaoArquivo.cs
=> Ajuste de retorno de status e remoção de enum intermediário

SME.CDEP.Infra.Dados/Repositorios/RepositorioImportacaoArquivo.cs
=> Deverá exibir os resultados independente do status

SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoDocumental.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoDocumental.cs, SME.CDEP.Aplicacao/UseCase/ExecutarImportacaoArquivoAcervoDocumentalUseCase.cs, SME.CDEP.Aplicacao/UseCase/Interface/IExecutarImportacaoArquivoAcervoDocumentalUseCase.cs, SME.CDEP.Infra.Servicos/Rabbit/RotasRabbit.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_documental.cs, SME.CDEP.Worker/WorkerRabbitMQ.cs
=> Segregando em fila a importação do acervo documental

SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoArteGrafica.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoArteGrafica.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoBibliografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoDocumental.cs, SME.CDEP.Aplicacao/UseCase/ExecutarImportacaoArquivoAcervoArteGraficaUseCase.cs, SME.CDEP.Aplicacao/UseCase/Interface/IExecutarImportacaoArquivoAcervoArteGraficaUseCase.cs, SME.CDEP.Infra.Servicos/Rabbit/RotasRabbit.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_arte_grafica.cs, SME.CDEP.Worker/WorkerRabbitMQ.cs, scripts/V48__ALTER_AUMENTAR_CAMPO_NOME_ASSUNTO_PARA_270.sql
=> Segregando em fila a importação do acervo artes gráficas

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoArteGrafica.cs
=> Corrigindo o nome da fila

SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoAudiovisual.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoAudiovisual.cs, SME.CDEP.Aplicacao/UseCase/ExecutarImportacaoArquivoAcervoAudiovisualUseCase.cs, SME.CDEP.Aplicacao/UseCase/Interface/IExecutarImportacaoArquivoAcervoAudiovisualUseCase.cs, SME.CDEP.Infra.Servicos/Rabbit/RotasRabbit.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_audiovisual.cs, SME.CDEP.Worker/WorkerRabbitMQ.cs
[AB#120394](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/120394)
=> Segregando em fila a importação do acervo audiovisuais

SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoFotografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoFotografico.cs, SME.CDEP.Aplicacao/UseCase/ExecutarImportacaoArquivoAcervoFotograficoUseCase.cs, SME.CDEP.Aplicacao/UseCase/Interface/IExecutarImportacaoArquivoAcervoFotograficoUseCase.cs, SME.CDEP.Infra.Servicos/Rabbit/RotasRabbit.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_fotografico.cs, SME.CDEP.Worker/WorkerRabbitMQ.cs
[AB#120394](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/120394)
=> Segregando em fila a importação do acervo fotográficos

SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoTridimensional.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoTridimensional.cs, SME.CDEP.Aplicacao/UseCase/ExecutarImportacaoArquivoAcervoTridimensionalUseCase.cs, SME.CDEP.Aplicacao/UseCase/Interface/IExecutarImportacaoArquivoAcervoTridimensionalUseCase.cs, SME.CDEP.Infra.Servicos/Rabbit/RotasRabbit.cs, SME.CDEP.IoC/RegistradorDeDependencia.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_tridimensional.cs, SME.CDEP.Worker/WorkerRabbitMQ.cs
[AB#120394](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/120394)
=> Segregando em fila a importação do acervo tridimensionais

SME.CDEP.Aplicacao/Servicos/Interface/IServicoImportacaoArquivoAcervoBibliografico.cs, SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoBibliografico.cs, SME.CDEP.Aplicacao/UseCase/ExecutarImportacaoArquivoAcervoArteGraficaUseCase.cs, SME.CDEP.Aplicacao/UseCase/ExecutarImportacaoArquivoAcervoAudiovisualUseCase.cs, SME.CDEP.Aplicacao/UseCase/ExecutarImportacaoArquivoAcervoBibliograficoUseCase.cs, SME.CDEP.Aplicacao/UseCase/ExecutarImportacaoArquivoAcervoDocumentalUseCase.cs, SME.CDEP.Aplicacao/UseCase/ExecutarImportacaoArquivoAcervoFotograficoUseCase.cs, SME.CDEP.Aplicacao/UseCase/ExecutarImportacaoArquivoAcervoTridimensionalUseCase.cs, SME.CDEP.Aplicacao/UseCase/Interface/IImportacaoArquivoAcervoArteGraficaAuxiliar.cs, SME.CDEP.Aplicacao/UseCase/Interface/IImportacaoArquivoAcervoAudiovisualAuxiliar.cs, SME.CDEP.Aplicacao/UseCase/Interface/IImportacaoArquivoAcervoBibliograficoAuxiliar.cs, SME.CDEP.Aplicacao/UseCase/Interface/IImportacaoArquivoAcervoDocumentalAuxiliar.cs, SME.CDEP.Aplicacao/UseCase/Interface/IImportacaoArquivoAcervoFotograficoAuxiliar.cs, SME.CDEP.Aplicacao/UseCase/Interface/IImportacaoArquivoAcervoTridimensionalAuxiliar.cs, SME.CDEP.TesteIntegracao/ConstantesTestes.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_arte_grafica.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_audiovisual.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_bibliografico.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_documental.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_fotografico.cs, SME.CDEP.TesteIntegracao/ImportacaoArquivo/Ao_fazer_manutencao_importacao_arquivo_acervo_tridimensional.cs, SME.CDEP.TesteIntegracao/Setup/RegistradorDependencias.cs
[AB#120394](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/120394)
=> Correção dos testes após a segregação da importação em filas

SME.CDEP.Aplicacao/Servicos/ServicoEvento.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs
[AB#120654](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/120654)
=> Evitando agendar visita em finais de semana

SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs
[AB#121474](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/121474)
=> Removido tratamento do login que deverá vir correto, sem tratamentos

SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs
[AB#121474](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/121474)
=> PREPROD - Fix/121474

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoFotografico.cs, SME.CDEP.Dominio/Constantes/MensagemNegocio.cs, SME.CDEP.Webapi/Controllers/ImportacaoArquivoAcervoFotograficoController.cs, scripts-prod/BUG121179/CORRIGIR_DATA_ACERVO_FOTOGRAFICO.sql
[AB#121179](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/121179)
=> PREPROD -- Fix/121179

SME.CDEP.Aplicacao/Servicos/ServicoImportacaoArquivoAcervoFotografico.cs
[AB#121179](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/121179)
=> Removendo quantidade de caracteres hardcode

scripts-prod/BUG121179/CORRIGIR_DATA_ACERVO_FOTOGRAFICO.sql
=> PREPROD - Corrigindo o script sql
